### ISSUE TITLE
New Cross Platform Alpha, Exception on Windows 10

### ISSUE THREAD

**Issue by G3N7** [JohannesHoppe/Mongo2Go#12]
Exception: Second path fragment must not be a drive or UNC name.

I am going to look into this tonight, but after updating to the alpha Mongo2Go no longer works for me locally.

**Comment by JohannesHoppe** [comment]
Hope you find the reason for this bug. Exactly because of bugs like this i stayed with all machines on Windows 8.1 (so I can't test this! :disappointed:)

//cc @krippz

**Comment by G3N7** [comment]
So this is due to the issue detailed here:
https://github.com/JohannesHoppe/Mongo2Go/issues/13
