### ISSUE TITLE
Changed binaries to be the SSL version, causes errors for missing DLLs

### ISSUE THREAD

**Issue by G3N7** [JohannesHoppe/Mongo2Go#15]
So after working through the other issue, I find that I started getting these errors:
![image](https://cloud.githubusercontent.com/assets/7042297/17237931/69f5513a-5514-11e6-997d-39b1fa3c9690.png)

They seem to be related to changing from the Non-SSL distribution of MongoDB to the SSL version:
https://github.com/JohannesHoppe/Mongo2Go/commit/cd845235f34e5d9ca17dcbd8c40f95624c354399

**Comment by G3N7** [comment]
I am swapping to the Non SSL locally to verify

**Comment by JohannesHoppe** [comment]
Yeah, there was no good reason to take the SSL version. Shame on me! =)

**Comment by G3N7** [comment]
haha, no worries, I noticed one of the links I followed to get to the downloads page had a query param that meant it only showed SSL versions and realized what was up.  Thanks for all the time you have put into this, it is a great tool.
