### ISSUE TITLE
Can we have an overload on Start() that resets the data?

### ISSUE THREAD

**Issue by cottsak** [JohannesHoppe/Mongo2Go#16]
So that I can be assured that each test run, the state of the store is the same.

**Comment by JohannesHoppe** [comment]
That's basically the idea of MongoDB. Each time you `Start()` you should have an empty database. Then it's up to you to fill the DB with test data.

**Comment by cottsak** [comment]
@JohannesHoppe Ok. Then the issue is with https://github.com/JohannesHoppe/Mongo2Go/issues/17 then. I'll close this one.
