### ISSUE TITLE
Any chance we could update to 3.2.6

### ISSUE THREAD

**Issue by G3N7** [JohannesHoppe/Mongo2Go#6]
I am trying to use `$lookup` and would love to be able to test using mongo2go.  I am going to look at how to update this but if its easy for y'all to do it, I would certainly appreciate it.

**Comment by G3N7** [comment]
I cannot seem to get some of the tests to work locally, so I am having trouble validating my changes.

**Comment by JohannesHoppe** [comment]
Sent me a pull request, I will test & merge then! :-)

**Comment by G3N7** [comment]
#7 Submitted, thank you!

**Comment by JohannesHoppe** [comment]
Uploaded to Nuget. I hade to change a few additional things.
Can you confirm that it works for you?

**Comment by G3N7** [comment]
This is working great, thank you sir.
