### ISSUE TITLE
Getting port on mono fails

### ISSUE THREAD

**Issue by krippz** [JohannesHoppe/Mongo2Go#9]
Hi we would like to use Mongo2Go in a cross platform environment, but we hit bit of a snag since:
`IPEndPoint[] tcpConnInfoArray = IPGlobalProperties.GetIPGlobalProperties().GetActiveTcpListeners();`
is not implemented by mono :( 

I was thinking of providing a mono compatible implementation of this, how does that sound?

/cheers
Krippz

**Comment by JohannesHoppe** [comment]
Hello,

that sounds awesome! :+1: 

Unfortunately I'm completely busy with my current projects – and family-related stuff. So I can't help here. However, I could offer write access to this repository as well as write access to Nuget. If this helps.

I'm also cool if you prefer to fork Mongo2Go. I never stated a license explicitly. But technically Mongo2Go should inherit the license from the MongoDB binaries ([GNU-AGPL-3.0](https://github.com/JohannesHoppe/Mongo2Go/blob/master/tools/mongodb-win32-x86_64-2008plus-3.2.6/GNU-AGPL-3.0)).

Cheers,
Johannes

**Comment by JohannesHoppe** [comment]
FYI, another project is right now running MongoDB on Travis-CI (mono):
see https://github.com/JohannesHoppe/Mongo2Go/pull/8
